version: '3.9'

build:
  db:
    image: mysql:8.0.34
    ports:
      - '3307:3306'
    volumes:
      - './schema:/docker-entrypoint-initdb.d'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=app
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=app
